### ISSUE TITLE
Authorization 

### ISSUE THREAD

**Issue by muezis** [JoshLmao/Genify#10]
Hi. I'm sure you know about this, and if I understand correctly - it's because your site doesn't have a server. But I decided to report about it))

Authorization is reset. But this only happens if I close browser. If browser always open, everything is fine. But even if I close and open browser immediately after authorization - I will get an error again. It's strange that this issue didn't occur during the white screen issue...

https://imgur.com/a/cizuv1a

**Comment by JoshLmao** [comment]
Yep, I've had this during dev and it's always been at the back of my mind to fix it. I've just fixed it (34a8c55d35765fd43f0020a30baf4943a65b7f74) and will be in the next update (v3.0.4) once I've finished some other features

**Comment by muezis** [comment]
> Yep, I've had this during dev and it's always been at the back of my mind to fix it. I've just fixed it ([34a8c55](https://github.com/JoshLmao/Genify/commit/34a8c55d35765fd43f0020a30baf4943a65b7f74)) and will be in the next update (v3.0.4) once I've finished some other features

I'm afraid it's getting worse. Now when I open browser, I'm not automatically redirected to the main page. Now just a white screen on https://genify.joshlmao.com/app . And for the site to work, I have to manually go to https://genify.joshlmao.com/ and click "Sign In"

**Comment by JoshLmao** [comment]
Hm, it shouldn't be getting worse. Can you take a look at the console (F12) and see if there are any errors or warnings? Like i've said before, the white screen is a crash which is bad. Also, what browser do you use?

**Comment by muezis** [comment]
> Hm, it shouldn't be getting worse. Can you take a look at the console (F12) and see if there are any errors or warnings? Like i've said before, the white screen is a crash which is bad. Also, what browser do you use?

On version 3.0.3 When I opened browser on the tab https://genify.joshlmao.com/app I was automatically redirected to https://genify.joshlmao.com/ and I had to click "Sign In" button. But now, on version 3.0.4 when opening browser on the tab https://genify.joshlmao.com/app I get just a white screen, and even refresh page doesn't help, I have to manually go to https://genify.joshlmao.com/ and click "Sign In" button.

https://imgur.com/a/z2O4eoa - Gif. How it happens.
https://imgur.com/a/NLDydiu - error

I'm using Yandex Browser. Based on Chromium.

**Comment by JoshLmao** [comment]
Okay, thanks for all the info. I changed to using a cookie library as of last version and it seems to have set cookies to be deleted once the browser closes, even though I fixed it a commit ago 🤦‍♂️

I'll get to fixing it now and push a update asap

**Comment by JoshLmao** [comment]
Updated to v3.0.5 with a fix. I'll leave this open for you to close if this fixes it

**Comment by muezis** [comment]
Perfect. Thanks a lot. Now it works awesome. Great work))
