### ISSUE TITLE
White space between verses missing/"&amp" should be displayed as &

### ISSUE THREAD

**Issue by muezis** [JoshLmao/Genify#11]
Hi. Often the space between verses isn't displayed. But it's strange that refreshing page can help (although not the first time). And similar problem with the "&" character, it's sometimes displayed as "&amp".

https://yadi.sk/i/hv82R6z3KS1vJg
On the video, the space disappeared only for one verse, but this can happen with all the verses. On any songs.

**Comment by JoshLmao** [comment]
The space missing is related to some filtering of the lyrics that happens before showing. And I'm guessing '&amp' is what is displayed in raw HTML from Genius so a simple replace will fix that

**Comment by JoshLmao** [comment]
Fixed this now. Will be in the next update 😉
