### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by muezis** [JoshLmao/Genify#12]
If your site is open (and Spotify too), but I don't listen to music at least 2 hours, then when I start - lyrics just won't load. It's noteworthy that player works perfectly. But lyrics... Just endless loading. Only refreshing page helps.

https://yadi.sk/i/Gg7vwrVExOU9Xw
(Yea, I should probably give you a screenshot of the console, but I thought about it already after refreshing page🤦‍♂️)

**Comment by JoshLmao** [comment]
I'm working on a new feature for when no music is playing and I've had this happen to me a couple times too. Will be fixed in the next update 😉

And yeah, the console would be nice to see since I only print vital info to it. But it's okay, reporting it is still great. I appreciate it

**Comment by JoshLmao** [comment]
I fixed this in 1e7ead6edb5a8d163ec28b27b2d595f502ccd27c and should be in v3.0.7
