### ISSUE TITLE
Support for the space bar and arrows

### ISSUE THREAD

**Issue by FiftyFour7250** [JoshLmao/Genify#15]
Hey, if you have time, and it's not so difficult, could you please add support for the space bar and arrows for the player? I mean a pause on the space bar, and rewind by arrows for five seconds, like on YouTube. But exactly five seconds. Just you know, if I want to listen to some just said line again - it would be more convenient to use the keys)

**Comment by JoshLmao** [comment]
Hey, sorry for the delayed response. I like this idea and I often use it for YouTube too. I'll get around to adding it asap :D

**Comment by JoshLmao** [comment]
Hey. I got around to added this in v3.0.10 (f9fe005b1357b2a2e3047f3e36013da8a0ebc4f4). Try it out and if you get any more suggestions for keyboard shortcuts, let me know 😉

**Comment by FiftyFour7250** [comment]
Yes! It's works perfect, thank you so much for not saying "This is beyond the scope of the project"))
