### ISSUE TITLE
Information about editing with account on Genius

### ISSUE THREAD

**Issue by FiftyFour7250** [JoshLmao/Genify#18]
I created account on Genius yesterday, and now all lyrics looks like this... 

![image](https://user-images.githubusercontent.com/78786088/125985925-2682fe2a-4acb-4f7d-8520-8be8ce64b0f7.png)

It's not terrible, but decided to let you know)

**Comment by JoshLmao** [comment]
Thanks for reporting this. It's related to the new Genius layout that is constantly getting updated. A change I did for #17 must have caused this. I'll get to fixing it
