### ISSUE TITLE
Rewind 

### ISSUE THREAD

**Issue by muezis** [JoshLmao/Genify#3]
This is perfect. But one thing is missing - rewind by clicking on the playback bar (as it works in all players). Please add it. I learn the language by reading the lyrics, and it is important for me to be able to rewind and pause to listen a particular phrase again.

**Comment by JoshLmao** [comment]
Apologies for the slow reply, I didn't have email notifications on for this repo. 

I agree. I want to rewrite the whole thing using React which shouldn't take long and plan on implementing rewind capabilities as well as more

**Comment by muezis** [comment]
This is perfect. Thank you so much))

**Comment by JoshLmao** [comment]
Haha, you noticed I'm updating the site right now! Yeah, I completely rewrote it in a week for this and for more improvements. Happy you like it 😉
