### ISSUE TITLE
Bug - Special characters

### ISSUE THREAD

**Issue by muezis** [JoshLmao/Genify#7]
Hey, songs with special characters don't open the lyrics.

https://imgur.com/a/CWmmx7r
https://imgur.com/a/XDI40ML
https://imgur.com/a/2Orrz2Y

**Comment by JoshLmao** [comment]
Hi, I've found the same happen for me too. I'm working on a fix but it's a weird problem so might take some time

**Comment by JoshLmao** [comment]
I managed to fix this but it was a funny one. Turns out the space char is different in the Genius API, nothing related to the special chars, haha. Fixed in 320e43f1723f488804b2882c4957d62396fffa69

**Comment by muezis** [comment]
> I managed to fix this but it was a funny one. Turns out the space char is different in the Genius API, nothing related to the special chars, haha. Fixed in [320e43f](https://github.com/JoshLmao/Genify/commit/320e43f1723f488804b2882c4957d62396fffa69)

Still doesn't work :c

**Comment by JoshLmao** [comment]
Yeah, because I haven't updated the live build. I do a bunch of fixes or a feature then update. Click on the version at the top of the page for info on the latest changes
